class App:

    def __init__(self, name, clips=(), actions=()):
        self.name = name # app name
        self.clips = clips
        self.actions = actions

    def __repr__(self):
        """
        External representation: Python program
        :return: String
        """

        rtr = """// generated by CinEditorML

%s

%s""" % ("\n".join(map(lambda c: c.declare(), self.clips)),
        "\n".join(map(lambda a: a.execute(), self.actions)))
        return rtr
