class App:

	def __init__(self, name, clips=(), actions=(), clipFinal=None):
		self.name = name # app name
		self.clips = clips
		self.actions = actions
		self.clipFinal = clipFinal

	def get_clipFinal(self):
		return self.clipFinal

	def set_clipFinal(self, clipFinal):
		self.clipFinal = clipFinal

	def __repr__(self):
		"""
		External representation: Python program
		:return: String
		"""

		rtr = """// generated by CinEditorML

%s

%s""" % ("\n".join(map(lambda c: c.declare(), self.clips)),
		"\n".join(map(lambda a: a.execute(), self.actions)))
		return rtr
